item {
    id : 1
    name : 'frame'
}

item {
    id : 2
    name : 'saddle'
}

item {
    id : 3
    name : 'wheel'
}

item {
    id : 4
    name : 'chain' 
}

item {
    id : 5
    name : 'crank'
}

item {
    id : 6
    name : 'chainring'
}

item {
    id : 7
    name : 'seatpost'
}

item {
    id : 8
    name : 'handle'
}